### ISSUE TITLE
Update for latest PSFalcon?

### ISSUE THREAD

**Issue by kimberlyrei** [bkremian/Scripts#1]
Looks like the most recent version of PSFalcon broke the get artifacts script.

**Comment by bk-cs** [comment]
Yes, that's correct -- PSFalcon v2 is drastically different than v1, so any scripts that use v1 will no longer work.

I'll take note of this and update the script to work with either version, but for the time being I recommend keeping PSFalcon v1 if you're using the GetArtifacts script regularly.

You can force the installation of PSFalcon v1 using the following command:
```powershell
Install-Module -Name PSFalcon -RequiredVersion 1.4.2 -Scope CurrentUser -SkipPublisherCheck
```

As long as PSFalcon v1 is installed, you can force that specific version to load:
```powershell
Import-Module -Name PSFalcon -RequiredVersion 1.4.2
```

Once you force the load of v1.4.2, the GetArtifacts script should continue to work like before. Once I update the script, it will process properly for either version. Please let me know if that solves your problem for now, or if you have any issues!

**Comment by kimberlyrei** [comment]
Perfect - that worked, thank you for your help!

**Comment by bkremian** [comment]
I've updated the script to work with PSFalcon v2.0.0 and the new IOC APIs that were released a few weeks ago. Please let me know if you run into any issues in your testing.
